# Generated by Django 2.0.1 on 2018-06-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likecount',
            options={'verbose_name': '点赞数', 'verbose_name_plural': '点赞数'},
        ),
        migrations.AlterModelOptions(
            name='likerecord',
            options={'verbose_name': '点赞记录', 'verbose_name_plural': '点赞记录'},
        ),
    ]
