# Generated by Django 2.0.4 on 2018-04-14 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBlog', '0005_blog_readed_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='readed_num',
            new_name='read_num',
        ),
    ]
