# Generated by Django 2.0.4 on 2018-04-14 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBlog', '0006_auto_20180414_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='read_num',
        ),
    ]
