# Generated by Django 2.0.4 on 2018-04-25 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBlog', '0009_auto_20180425_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tag_name',
            new_name='blog_tag',
        ),
    ]
