# Generated by Django 2.0.1 on 2018-05-30 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBlog', '0010_auto_20180425_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogtag',
            options={'verbose_name': '文章标签', 'verbose_name_plural': '文章标签'},
        ),
        migrations.AlterModelOptions(
            name='blogtype',
            options={'verbose_name': '文章分类', 'verbose_name_plural': '文章分类'},
        ),
    ]
