# Generated by Django 2.0.1 on 2018-06-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBlog', '0011_auto_20180530_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': '博客文章', 'verbose_name_plural': '博客文章'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
